# Site settings
title: Roger Stringer
email: roger.stringer@me.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Roger Stringer, and I’m a DevOps Engineer, full-stack software developer, writer, and speaker in Penticton, British Columbia, Canada.
  This blog is where I write and share. You will see everything from reviews, posts about tech and design, to food.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rogerstringer.com" # the base hostname & protocol for your site
twitter_username: freekrai
github_username:  freekrai

twitter:
  username: "@freekrai"

facebook:
  app_id: "474703915878478"
  publisher: "1416546778590314"
  admins: "604781976"


social:
  name: Roger Stringer
  links:
    - https://twitter.com/freekrai
    - https://www.facebook.com/rogerwlstringer
    - https://plus.google.com/+RogerStringer
    - https://github.com/freekrai
    - https://www.instagram.com/freekrai

disqus:
  shortname: freekrai

google_plus_id: RogerStringer
ga_username: UA-126274-13

collections:
  - resume_positions

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "footnotes"]
highlighter: rouge
paginate: 10
permalink: pretty

github:
  repo: freekrai/freekrai.github.io
  branch: master

gems:
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag
